baseurl: https://santhiago-cristiano.github.io/site/
languageCode: en
DefaultContentLanguage: br
title: Santhiago Cristiano
theme: beautifulhugo
metaDataFormat: yaml
summarylength: 20
enableEmoji: yes
enableRobotsTXT: yes
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
publishDir: docs
Params:
  comments: yes
  commit: no
  dateFormat: 02/01/2006
  delayDisqus: yes
  favicon: img/myfavicon.ico
  logo: img/SC.png
  mainSections:
    - post
    - posts
    #- projetos
  readingTime: no
  rss: no
  showRelatedPosts: yes
  socialShare: yes
  #homeTitle: Título
  subtitle: Seja bem vindo (a) ao meu site pessoal. Aqui escrevo sobre R e Python.
  useHLJS: yes
  wordCount: no
Author:
  #500px: username
  #bandcamp: username
  #bitbucket: username
  #codepen: username
  email: santhiago_cristiano@hotmail.com
  #facebook: username
  github: santhiago-cristiano
  #gitlab: username
  #instagram: username
  #itchio: username
  #kaggle: username
  linkedin: username
  #mastodon: url
  name: Santhiago Cristiano
  #paypal: username
  #reddit: username
  #slack: username
  #snapchat: username
  #soundcloud: username
  #spotify: username
  #stackoverflow: users/XXXXXXX/username
  #telegram: username
  #twitter: username
  #vk: username
  #website: yourwebsite.com
  #weibo: username
  #xing: username
  #youtube: user/username
menu:
  main:
    - name: Posts
      url: ''
      weight: 1
    #- name: Projetos
    #  url: /projetos/
    #  weight: 2
    - name: Sobre
      url: page/about/
      weight: 3
    - name: Contato
      url: page/contact/
      weight: 4
    #- identifier: samples
    #  name: Samples
    #  weight: 2
    #- name: Big Image Sample
    #  parent: samples
    #  url: post/2017-03-07-bigimg-sample
    #  weight: 1
    #- name: Math Sample
    #  parent: samples
    #  url: post/2017-03-05-math-sample
    #  weight: 2
    #- name: Code Sample
    #  parent: samples
    #  url: post/2016-03-08-code-sample
    #  weight: 3
    - name: Tags
      url: tags
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true
